version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"      # S3 API
      - "9001:9001"      # MinIO Console UI
    environment:
      MINIO_ROOT_USER: minioadmin     # Change for production
      MINIO_ROOT_PASSWORD: minioadmin # Change for production
    command: server /data --console-address ":9001"
    volumes:
      - ./.volumes/minio_data:/data
    restart: unless-stopped
