name: Build & Push Docker Image to GHCR

on:
  push:
    branches: [ master ]
  pull_request:
    types: [synchronize, opened, reopened]
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract version and commit sha
        id: vars
        run: |
          VERSION=$(jq -r .version package.json)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.PACKAGE_VERSION }}
            ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}

  trigger-deploy:
    runs-on: ubuntu-24.04
    needs: build-and-push

    steps:
      - name: Trigger Dokploy Deployment
        run: |
          curl -X 'POST' \
          'http://31.97.206.20:3000/api/trpc/application.deploy' \
          -H 'accept: application/json' \
          -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
          -H 'Content-Type: application/json' \
          -d '{
              "json":{
                  "applicationId": "${{ secrets.DOKPLOY_APP_ID }}",
              }
          }'
